/*
  # Add English and Welsh Mountains
  
  This migration adds:
  - Lake District Wainwrights and major peaks
  - Welsh mountains (Snowdonia and Brecon Beacons)
  - Peak District and Yorkshire Dales peaks
  - English Hewitts and Nuttalls
*/

-- Lake District Mountains (Wainwrights and major peaks)
INSERT INTO mountains (name, slug, height_meters, height_feet, latitude, longitude, region, county, prominence_meters, grid_reference, national_park, area, difficulty_rating, parent_range, is_wainwright, is_hewitt, is_nuttall, is_marilyn, description, classification) VALUES
('Great Gable', 'great-gable', 899, 2949, 54.487222, -3.227500, 'England', 'Cumbria', 299, 'NY 211103', 'Lake District National Park', 'Central Fells', 'Moderate', 'Lake District', true, true, true, false, 'Great Gable is one of the Lake District''s most iconic mountains. Its distinctive shape dominates the head of Wasdale, and it was gifted to the National Trust as a war memorial.', 'Wainwright'),
('Skiddaw', 'skiddaw', 931, 3054, 54.649722, -3.147778, 'England', 'Cumbria', 709, 'NY 260291', 'Lake District National Park', 'Northern Fells', 'Easy', 'Lake District', true, true, true, true, 'Skiddaw is one of the Lake District''s most prominent mountains and one of the easiest to climb. The mountain overlooks Keswick and Derwentwater.', 'Wainwright'),
('Blencathra', 'blencathra', 868, 2848, 54.646111, -3.037500, 'England', 'Cumbria', 558, 'NY 323277', 'Lake District National Park', 'Northern Fells', 'Moderate', 'Lake District', true, true, true, true, 'Blencathra, also known as Saddleback, has several ridges offering varied routes. Sharp Edge provides one of the Lake District''s finest scrambles.', 'Wainwright'),
('Bowfell', 'bowfell', 902, 2960, 54.446389, -3.095556, 'England', 'Cumbria', 252, 'NY 245064', 'Lake District National Park', 'Southern Fells', 'Moderate', 'Lake District', true, true, true, false, 'Bowfell is a beautiful mountain at the head of Langdale. The summit is a rocky pyramid with excellent views, and the route via The Band is classic.', 'Wainwright'),
('Coniston Old Man', 'coniston-old-man', 803, 2635, 54.360000, -3.095000, 'England', 'Cumbria', 493, 'SD 272978', 'Lake District National Park', 'Southern Fells', 'Moderate', 'Lake District', true, true, true, false, 'Coniston Old Man towers over the village of Coniston and its lake. Mining remains on its slopes tell of its industrial past, while the summit gives superb views.', 'Wainwright'),
('Pillar', 'pillar', 892, 2927, 54.504167, -3.277778, 'England', 'Cumbria', 242, 'NY 171121', 'Lake District National Park', 'Western Fells', 'Moderate', 'Lake District', true, true, true, false, 'Pillar is one of the great Lake District mountains, with the famous Pillar Rock on its northern face. The summit gives excellent views of the western fells.', 'Wainwright'),
('High Street', 'high-street', 828, 2717, 54.507500, -2.901667, 'England', 'Cumbria', 188, 'NY 441110', 'Lake District National Park', 'Far Eastern Fells', 'Easy', 'Lake District', true, true, true, false, 'High Street follows a Roman road and has one of the Lake District''s longest summit ridges. The mountain offers easy walking with extensive views.', 'Wainwright'),
('Haystacks', 'haystacks', 597, 1959, 54.491944, -3.222778, 'England', 'Cumbria', 127, 'NY 193131', 'Lake District National Park', 'Western Fells', 'Moderate', 'Lake District', true, false, false, false, 'Despite its modest height, Haystacks was Alfred Wainwright''s favorite mountain. His ashes were scattered here, and the summit overlooks Innominate Tarn.', 'Wainwright'),
('Fairfield', 'fairfield', 873, 2864, 54.486944, -2.980833, 'England', 'Cumbria', 303, 'NY 359117', 'Lake District National Park', 'Eastern Fells', 'Moderate', 'Lake District', true, true, true, false, 'Fairfield is the highest point of the popular Fairfield Horseshoe walk from Ambleside. The mountain has a broad summit plateau.', 'Wainwright'),
('Grasmoor', 'grasmoor', 852, 2795, 54.571111, -3.297778, 'England', 'Cumbria', 522, 'NY 175203', 'Lake District National Park', 'Northwestern Fells', 'Moderate', 'Lake District', true, true, true, true, 'Grasmoor is the highest of the northwestern fells. The mountain has steep sides, particularly Dove Crags, and commands excellent views.', 'Wainwright'),
('Crinkle Crags', 'crinkle-crags', 859, 2818, 54.433333, -3.087778, 'England', 'Cumbria', 209, 'NY 249049', 'Lake District National Park', 'Southern Fells', 'Moderate', 'Lake District', true, true, true, false, 'Crinkle Crags is a mountain with five main "crinkles" or summits. The route involves scrambling and is one of Lakeland''s finest ridge walks.', 'Wainwright'),
('Great End', 'great-end', 910, 2986, 54.467778, -3.185833, 'England', 'Cumbria', 160, 'NY 226083', 'Lake District National Park', 'Central Fells', 'Moderate', 'Lake District', true, true, true, false, 'Great End is at the head of Borrowdale with impressive crags. Often climbed with Scafell Pike, it gives spectacular views down the valley.', 'Wainwright'),
('Ill Crag', 'ill-crag', 935, 3068, 54.459444, -3.197500, 'England', 'Cumbria', 35, 'NY 223072', 'Lake District National Park', 'Southern Fells', 'Hard', 'Lake District', true, true, true, false, 'Ill Crag is part of the Scafell massif and England''s third highest peak. It''s usually climbed as part of a round from Wasdale or Borrowdale.', 'Wainwright'),

-- Welsh Mountains (Snowdonia)
('Carnedd Llewelyn', 'carnedd-llewelyn', 1064, 3491, 53.160000, -3.965833, 'Wales', 'Gwynedd', 614, 'SH 683644', 'Snowdonia National Park', 'Carneddau', 'Moderate', 'Carneddau', false, true, true, true, 'Carnedd Llewelyn is the second highest mountain in Wales. The vast summit area is part of the wild Carneddau range, popular with wild campers.', 'Hewitt'),
('Carnedd Dafydd', 'carnedd-dafydd', 1044, 3425, 53.176111, -3.985000, 'Wales', 'Gwynedd', 124, 'SH 663630', 'Snowdonia National Park', 'Carneddau', 'Moderate', 'Carneddau', false, true, true, false, 'Carnedd Dafydd is part of the main Carneddau ridge. The mountain is often climbed with Carnedd Llewelyn, forming a fine ridge walk.', 'Hewitt'),
('Glyder Fawr', 'glyder-fawr', 1001, 3284, 53.110000, -4.029722, 'Wales', 'Gwynedd', 641, 'SH 642579', 'Snowdonia National Park', 'Glyderau', 'Moderate', 'Glyderau', false, true, true, true, 'Glyder Fawr is the highest of the Glyderau range. The summit area has bizarre rock formations, including Cantilever Stone, one of Wales'' most photographed features.', 'Hewitt'),
('Glyder Fach', 'glyder-fach', 994, 3261, 53.108333, -4.003611, 'Wales', 'Gwynedd', 124, 'SH 656583', 'Snowdonia National Park', 'Glyderau', 'Moderate', 'Glyderau', false, true, true, false, 'Glyder Fach has a rocky summit with the famous Cantilever Stone. The summit castle of rocks provides shelter and excellent scrambling opportunities.', 'Hewitt'),
('Tryfan', 'tryfan', 918, 3010, 53.098333, -3.992778, 'Wales', 'Gwynedd', 458, 'SH 664594', 'Snowdonia National Park', 'Glyderau', 'Hard', 'Glyderau', false, true, true, false, 'Tryfan is one of Wales'' most famous mountains, requiring scrambling to reach the summit. Adam and Eve, two monoliths on the summit, are traditionally jumped between.', 'Hewitt'),
('Y Garn', 'y-garn-glyderau', 947, 3107, 53.105833, -4.052500, 'Wales', 'Gwynedd', 207, 'SH 631596', 'Snowdonia National Park', 'Glyderau', 'Moderate', 'Glyderau', false, true, true, false, 'Y Garn overlooks Llyn Ogwen and has a distinctive pyramidal shape. The Devil''s Kitchen cleft on the northeast face is a famous climbing venue.', 'Hewitt'),
('Elidir Fawr', 'elidir-fawr', 924, 3031, 53.125833, -4.059722, 'Wales', 'Gwynedd', 424, 'SH 613613', 'Snowdonia National Park', 'Glyderau', 'Moderate', 'Glyderau', false, true, true, false, 'Elidir Fawr is the northernmost of the major Snowdonia peaks. Inside the mountain is the Dinorwig Power Station, a massive pumped-storage facility.', 'Hewitt'),
('Crib Goch', 'crib-goch', 923, 3028, 53.078889, -4.065833, 'Wales', 'Gwynedd', 73, 'SH 624551', 'Snowdonia National Park', 'Snowdon Massif', 'Hard', 'Snowdon Range', false, true, true, false, 'Crib Goch is the most famous knife-edge ridge in Wales. The exposed scramble is the classic route up Snowdon but requires a good head for heights.', 'Hewitt'),
('Moel Siabod', 'moel-siabod', 872, 2861, 53.060000, -3.906944, 'Wales', 'Gwynedd', 622, 'SH 705546', 'Snowdonia National Park', 'Moelwynion', 'Moderate', 'Moelwynion', false, true, true, true, 'Moel Siabod is an isolated peak offering superb views of Snowdon. The mountain is easily accessible from Capel Curig and provides excellent walking.', 'Hewitt'),
('Aran Fawddwy', 'aran-fawddwy', 905, 2970, 52.797778, -3.697222, 'Wales', 'Gwynedd', 605, 'SH 862223', 'Snowdonia National Park', 'Aran', 'Moderate', 'Aran Mountains', false, true, true, true, 'Aran Fawddwy is the highest peak in the Aran range and southern Snowdonia. The mountain is more remote and less visited than the northern peaks.', 'Hewitt'),

-- Brecon Beacons (Wales)
('Corn Du', 'corn-du', 873, 2864, 51.884444, -3.437500, 'Wales', 'Powys', 53, 'SO 007213', 'Brecon Beacons National Park', 'Brecon Beacons', 'Easy', 'Brecon Beacons', false, true, true, false, 'Corn Du is the twin summit of Pen y Fan, separated by a small col. The two are usually climbed together on the most popular route in the Brecon Beacons.', 'Hewitt'),
('Cribyn', 'cribyn', 795, 2608, 51.893889, -3.423889, 'Wales', 'Powys', 95, 'SO 022213', 'Brecon Beacons National Park', 'Brecon Beacons', 'Easy', 'Brecon Beacons', false, true, true, false, 'Cribyn has a sharp pointed summit and is often climbed with Pen y Fan. The mountain forms part of the classic Brecon Beacons horseshoe walk.', 'Hewitt'),
('Fan Fawr', 'fan-fawr', 734, 2408, 51.884444, -3.557500, 'Wales', 'Powys', 334, 'SN 969192', 'Brecon Beacons National Park', 'Fforest Fawr', 'Moderate', 'Brecon Beacons', false, true, true, false, 'Fan Fawr is in the western Brecon Beacons. The mountain has a distinctive shape and offers good walking with less crowds than Pen y Fan.', 'Hewitt'),

-- Peak District & Yorkshire Dales
('Kinder Scout', 'kinder-scout', 636, 2087, 53.387500, -1.873056, 'England', 'Derbyshire', 336, 'SK 085876', 'Peak District National Park', 'Dark Peak', 'Moderate', 'Peak District', false, false, false, true, 'Kinder Scout is the highest point in the Peak District. The plateau is famous for the Mass Trespass of 1932, a pivotal moment in the campaign for access to open country.', 'Marilyn'),
('Bleaklow', 'bleaklow', 633, 2077, 53.450833, -1.859722, 'England', 'Derbyshire', 293, 'SK 093959', 'Peak District National Park', 'Dark Peak', 'Moderate', 'Peak District', false, false, false, true, 'Bleaklow is a wild peat moorland plateau. The summit area can be boggy, but the walk offers solitude and great views over the Dark Peak.', 'Marilyn'),
('Whernside', 'whernside', 736, 2415, 54.229722, -2.420833, 'England', 'North Yorkshire', 306, 'SD 738814', 'Yorkshire Dales National Park', 'Three Peaks', 'Moderate', 'Yorkshire Dales', false, true, true, false, 'Whernside is the highest of the Yorkshire Three Peaks. The walk along the ridge from Ribblehead Viaduct is spectacular, with panoramic views.', 'Hewitt'),
('Ingleborough', 'ingleborough', 723, 2372, 54.158333, -2.425833, 'England', 'North Yorkshire', 393, 'SD 741745', 'Yorkshire Dales National Park', 'Three Peaks', 'Moderate', 'Yorkshire Dales', false, true, true, true, 'Ingleborough has a distinctive flat summit plateau that was once an Iron Age hill fort. It''s the second peak in the Yorkshire Three Peaks challenge.', 'Hewitt')
ON CONFLICT (slug) DO NOTHING;